services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=vivavis_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
    networks:
      - mynetwork

  app:  # Your application service
    image: 'vivavis-app-image'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vivavis_db'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
